### ISSUE TITLE
Debian package should depend on Java 8 package

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-assembly#107]

**Comment by egli** [comment]
Sorry, I thought a bug is only closed if the change lands in master in the corresponding repo when you add a Fixes #nnn to the commit message.

**Comment by bertfrees** [comment]
Yeah, strange, thought so too.

**Comment by bertfrees** [comment]
The start script (bin/pipeline2) should probably also check for Java version 1.8 instead of 1.7.

**Comment by bertfrees** [comment]
The start script (bin/pipeline2) should probably also check for Java version 1.8 instead of 1.7.

**Comment by josteinaj** [comment]
Fixed in: https://github.com/daisy/pipeline-assembly/commit/10fce91a21370d774cb2a7d5e71e726a8e7fb2f8
