### ISSUE TITLE
Add EPUB3 sample

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-assembly#119]
E.g. we could take one from http://idpf.github.io/epub3-samples/samples.html

**Comment by bertfrees** [comment]
We decided to leave out the samples from future releases, but to provided a download link instead. We will put the samples in a separate repository and use the ZIP link that Github creates for us.

**Comment by bertfrees** [comment]
@rdeltour  needs to do this, I have insufficient permissions to add new repositories.

**Comment by bertfrees** [comment]
https://github.com/daisy/pipeline-samples

**Comment by bertfrees** [comment]
@rdeltour Which one should I take from http://idpf.github.io/epub3-samples/samples.html?

**Comment by rdeltour** [comment]
> Which one should I take from http://idpf.github.io/epub3-samples/samples.html?

Maybe "Accessible EPUB 3" ?

**Comment by bertfrees** [comment]
See PR: https://github.com/daisy/pipeline-samples/pull/1
