### ISSUE TITLE
NSIS fails when building dev-launcher

### ISSUE THREAD

**Issue by dkager** [daisy/pipeline-assembly#126]
With pipeline-assembly v1.10.0, NSIS 3.01:

```
[INFO] --- nsis-maven-plugin:1.0-alpha-1:make (default) @ assembly ---
[INFO] [MAKENSIS] !include: could not find: "../project.nsh"
[INFO] [MAKENSIS] Error in script "target/nsis/installer.nsi" on line 35 -- aborting creation process
```

**Comment by dkager** [comment]
Trivial fix by replacing slash with backslash in paths. But then when building dev-launcher:

```
[INFO] [MAKENSIS] File: "C:\Users\davykager\Snaekobbi\pipeline-assembly\target\pipeline2-1.10.0_win\daisy-pipeline" -> no files found.
[INFO] [MAKENSIS] Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
[INFO] [MAKENSIS]    /oname=outfile one_file_only)
[INFO] [MAKENSIS] Error in script "target/nsis/installer.nsi" on line 267 -- aborting creation process
```

**Comment by bertfrees** [comment]
Looks like NSIS plugin needs to be disabled in dev-launcher profile. There are a few other plugins  that are disabled in the profile already. This issue should be fixed properly in https://github.com/daisy/pipeline-assembly/issues/75 but in the meantime you/we can do something similar as those other plugins.

**Comment by dkager** [comment]
Will test and do a patch on Thursday.
