### ISSUE TITLE
Issues building from Windows

### ISSUE THREAD

**Issue by mccallum-sgd** [daisy/pipeline-assembly#135]
```
Build Failure: "Failed to execute goal org.codehaus.mojo:nsis-maven-plugin:1.0-alpha-1:make (default) on project assembly: Unable to execute makensis: Cannot run program "makensis" (in directory "D:\CS\GitHub\pipeline-assembly"): CreateProcess error=2, The system cannot find the file specified -> [Help 1] (http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException)".
```

Seems that it fails when attempting make goal with nsis-maven-plugin (line 1786 in the super POM).

[EDIT: unrelated ▼]
~~Snippet (line 1803):~~
```xml
<!-- !!!FIXME!!! -->
    <!-- This a gross hack to detach the `exe` artifact,
     since nsis-maven-plugin doesn't expose the option 
     to *not* attach the resulting executable -->~~
```
~~FIXME above indicates known compatibility issues.~~

**Comment by bertfrees** [comment]
Thanks. So apparently you are just missing the "makensis" tool. There is no cross-platform compatibility issue, as we first thought. I seem to have installed NSIS via `brew install nsis`. Windows users have to download it from http://nsis.sourceforge.net/Main_Page I guess. (This link is also mentioned in the README.md.)

The FIXME is unrelated by the way.

**Comment by bertfrees** [comment]
@dkager Hi. Sean is having an issue building the assembly project on Windows. He has installed NSIS and has changed the `%PATH%` environment variable, but nonetheless gets an error message saying Maven can't find makensis.exe. Specifying the path manually with `-Dmaven.nsis.exe="C:/Program Files/NSIS/makensis.exe"` did not help either. I know have done this so maybe you have a clue? A known issue with the Maven NSIS plugin? A permissions problem? Something wrong with the path (spaces, slashes)? Sean hasn't got that much experience with environment variables so he might even have done something basic wrong.

**Comment by dkager** [comment]
Does running makensis.exe from the command line work? I think you should use backslashes, but I seem to remember writing a patch for that which is in assembly 1.10.x.

**Comment by bertfrees** [comment]
Thanks Davy. @mccallum-sgd

**Comment by mccallum-sgd** [comment]
@dkager 
It's only recognized if I'm in the directory of the executable ("C:\Program Files (x86)\NSIS"). I also copy/pasted the path directly when using the manual option like so: `-Dmaven.nsis.exe="C:\Program Files (x86)\NSIS"`, so that shouldn't be the problem.

I believe I'm just setting the `%PATH%` variable incorrectly somehow. I've tried pointing to:
1. The whole NSIS folder -- "C:\Program Files (x86)\NSIS"
2. The Bin folder -- "C:\Program Files (x86)\NSIS\Bin"
3. The executable -- "C:\Program Files (x86)\NSIS\makensis.exe"
4. The executable in the Bin folder -- "C:\Program Files (x86)\NSIS\Bin\makensis.exe"

I tried all of these paths with the manual option `-Dmaven...` but no luck.

I've done this before for Java and Maven, so my understanding is that the first path should have worked, but in all cases running `makensis.exe /version` is not recognized as a command (outside of the executable's directory).

Here's what my `%PATH%` looks like:
![ice_screenshot_20170711-114107](https://user-images.githubusercontent.com/23219638/28081828-d91c30f8-662d-11e7-8ecf-f22f00f01c31.png)

**Comment by dkager** [comment]
I'm not in a position to check my PATH right now, but it sounds like yours is wrong. Launching cmd.exe and running makensis.exe should definitely work.

**Comment by mccallum-sgd** [comment]
Yes my mistake, I just realized the only thing I was doing wrong was not opening up a new cmd window every time I edited the `%PATH%`, so it was still using the old `%PATH%`. I set it to the whole NSIS folder and restarted cmd and everything works!

**Comment by mccallum-sgd** [comment]
Thanks for your help Davy even though it was such a simple mistake.

**Comment by bertfrees** [comment]
Thanks Davy.
