### ISSUE TITLE
Profile to build Docker images

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-assembly#139]
...and possibly to deploy to Docker hub.

See [#68](https://github.com/daisy/pipeline-assembly/pull/68#issuecomment-326633119).

There have been various other Docker related initiatives:

- https://github.com/snaekobbi/system#docker-image
- https://github.com/nlbdev?q=docker
- https://github.com/benetech/docker-pipeline2

but I think an official Docker image that we can use to distribute the software, and that people can base their custom images on, would be nice.

**Comment by josteinaj** [comment]
I've already created a docker image for the latest release, but it's something I'll have to update manually for each release:
- https://github.com/nlbdev/docker-daisy-pipeline
- https://hub.docker.com/r/nlbdev/daisy-pipeline/

I've also started working on a Dockerfile for the super repo. It can be set up on docker hub to build each time something is pushed to GitHub.

I'm not sure if it makes sense to make a maven profile for building docker images. To build a dockerfile you just do `docker build .`, and docker hub is not something you configure from the repo but from docker hub.

**Comment by bertfrees** [comment]
The idea of the profile and the docker-maven-plugin was to integrate everything nicely into the Maven build (including running some tests on the resulting image). See https://github.com/daisy/pipeline-assembly/pull/68. To integrate everything is not super important though.

Also at that time I was creating several images: one for server and webui in local setup, one for only the server and one for only the webui alone (remote setup), and even one for the cli. Now that everything related to the webui is removed from pipeline-assembly, a separate image for the webui does not make sense anymore, and an image for the cli does not seem really useful. Creating several images might not be a requirement anymore.

The fact that docker hub needs a Dockerfile in the top directory of the project is indeed also important to consider.

https://github.com/nlbdev/docker-daisy-pipeline builds the image using a released debian package, but I was rather thinking about first building the package on the fly, so that you can use the same Dockerfile to build an image of any revision. This is probably what you had in mind when thinking about a Dockerfile in the super project. This would indeed be useful, because it would allow to build an image even when there are internal snapshot dependencies.

Because the super project has multiple build artefacts, namely the server and the webui, I think a Dockerfile should include them both (like https://github.com/nlbdev/docker-daisy-pipeline does), or not exist at all. However I think it also makes sense to have separate images for the server and the webui. I would therefore like to have Dockerfiles inside the pipeline-assembly and pipeline-webui projects as well.

**Comment by josteinaj** [comment]
Dockerfile PR: daisy/pipeline#520

**Comment by bertfrees** [comment]
See PR: https://github.com/daisy/pipeline-assembly/pull/140
