### ISSUE TITLE
Simplify configuration

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-assembly#141]
See https://github.com/daisy/pipeline-assembly/pull/140#issuecomment-333507669, [(comment 2)](https://github.com/daisy/pipeline-assembly/pull/140#issuecomment-333510975)

- [x] Convert environment variables to Java system properties at run time
- [x] Rename all Pipeline properties to `org.daisy.pipeline.foo`
- [x] Document undocumented properties (http://daisy.github.io/pipeline/wiki/Configuration-Files). All the TTS related properties should be documented on the [TTS page](http://daisy.github.io/pipeline/modules/tts-common/tts-config.html) and should be linked from the general configuration page.
- [x] Make "job-local/dynamic" TTS config properties fall back to system properties instead of the "static" TTS config properties specified via `tts.config` system property. The static TTS config can still be used for other configuration like voices, CSS, etc. (handled by the so-called extensions).

---

Other todos moved to new issue: https://github.com/daisy/pipeline-assembly/issues/152

**Comment by egli** [comment]
See also [this so question](https://stackoverflow.com/questions/25036357/how-to-read-os-variables-from-java-not-system-properties) and [Spring Evironment](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/env/Environment.html) (don't know if this is usable without using Spring though)

**Comment by bertfrees** [comment]
In addition to mapping environment variables to Java system properties at run time, map Maven properties to the default values of Java system properties at build time.

**Comment by bertfrees** [comment]
First phase done in https://github.com/daisy/pipeline-framework/commit/6b02d70b64d8a06e9ee0ad27d4c1ef3afb83d52b, https://github.com/daisy/pipeline-framework/commit/5a68dee49ed439d0bd3b127d1d235b4dde4309ac, https://github.com/daisy/pipeline-assembly/commit/004003bf99038f6ad5c153083c736f18f511deab, https://github.com/daisy/pipeline-mod-tts/commit/c08c56a848cfd9ee39a8cac7adbf9610eb686c36, https://github.com/daisy/pipeline/commit/1afe2c89fec84f413291e330dd875c19e8e0eb58
