### ISSUE TITLE
eval-java issue on linux

### ISSUE THREAD

**Issue by NPavie** [daisy/pipeline-assembly#226]
I tried building the pipeline assembly project on 2 different Linux environments and it seems the makefile cannot be run any more.

OS tested : 
- Debian 12 with OpenJDK 17 / GNU make 4.3 for x86_64-pc-linux-gnu
- Ubuntu 18 over WSL with OpenJDK 11 / GNU Make 4.2.1 for x86_64-pc-linux-gnu

In all cases after cloning assembly, i have the following error : 
```bash
>$ make zip-linux
make/eval-java: 3: Syntax error: Unterminated quoted string
make/enable-java-shell.mk:16: *** "Java 8 is required to run this script".  Stop.
```

At first i add a permission issue this i resolved by a `chmod -R +x` on the make folder, but the error persisted.

If I try to run the `eval-java` tool on my Ubuntu, I get the following error :  `-bash: ./eval-java: cannot execute binary file: Exec format error`
I have slightly different error reported on my Debian : `-bash: ./eval-java : impossible d'exécuter le fichier binaire : Erreur de format pour exec()` (in english : `-bash: ./eval-java: cannot execute binary file: Exec format error for exec()`

The file utility confirms the problem 
```bash
>$ file ./eval-java
./eval-java: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```

Would it be possible to include a GNU/linux version of the eval-java tool in the repo ?

**Comment by bertfrees** [comment]
Yes, that's to be expected, it's a macOS executable. Ok, including a Linux executable makes sense.

**Comment by bertfrees** [comment]
@NPavie I've pushed something to the branch "assembly-build-linux". Could you please try it?
