### ISSUE TITLE
Use exec in bin/pipeline2

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-assembly#54]
It used to be exec but was changed to eval to ["cope with unescaped env variables"](https://github.com/daisy/pipeline-assembly/commit/303087ecab9a81675847ac0872c9258f61e25ac0), possibly in response to a [bug report from John Brugge](https://groups.google.com/forum/#!topic/daisy-pipeline-dev/D1OwpQ49OvY).

However, the nice thing about exec is that it replaces the shell without creating a new process. Without exec a child process is started. This causes trouble for the Debian package where we daemonised bin/pipeline2 using start-stop-daemon. The problem is that stopping the daemon doesn't seem to stop the child process.

**Comment by bertfrees** [comment]
Should we close this? because we already changed to eval exec in commit https://github.com/daisy/pipeline-assembly/commit/1bf37c1a2933b59c10fc265b1905487eb8d404db

**Comment by rdeltour** [comment]
Yes, I think it's fixed, good catch.
