### ISSUE TITLE
Redhat package

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-assembly#63]
Previously we decided to keep the ZIP as the default distribution and to keep the Debian package build in the deb profile which must be activated manually. We discussed the creation of packages for other Linux distros and [alien](https://joeyh.name/code/alien) was mentioned, but it was decided to do nothing until the feature was explicitly requested.

At some point MTM would like to have an RPM. Because they are currently creating packages for their own software they will get some experience with it so I can probably get advice from them.

**Comment by joeha480** [comment]
We are interested in this right now, because we're in the process of setting up DP2 servers with Puppet.

**Comment by bertfrees** [comment]
Has been done.
