### ISSUE TITLE
Include 'native' bundles only in mac/linux/windows distributions

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-assembly#67]
Applies to some braille modules, and possibly some TTS modules?

**Comment by rom1mouret** [comment]
Regarding the TTS modules:
- SAPI adapter should be packaged only with Windows distributions
- /usr/bin/say adapter should be packaged only with Mac distributions
- Acapela adapter is currently working for Unix systems only, but perhaps it is feasible to make it work on different systems using the same adapter, depending on Acapela's products

**Comment by bertfrees** [comment]
This is not completely fixed yet. The ZIP distribution now contains all the native bundles in `mac`/`linux`/`win` sub-directories of `modules`, plus the bundles specific to the current platform copied to the `modules` directory.
