### ISSUE TITLE
Issues with spaces in dtbook-to-epub3 transformation

### ISSUE THREAD

**Issue by kden** [daisy/pipeline-assembly#94]
Reproduction steps:
1. Downloaded pipeline2-1.9-webui_linux.zip from https://github.com/daisy/pipeline-assembly/releases/tag/v1.9
2. Started it up
3. Unzipped the "Great Painters" example book to /tmp/input/great_painters_dtbook_2005-3-test, which I got from http://www.daisy.org/sample-content#t5
4. Edited the greatpainters.xml file line 5 as follows

``` xml
<level2><h2><em>CHAPTER 1</em> <strong>THE LAST JUDGEMENT (MICHAEL ANGELO)</strong>
```
1. Ran the following command

``` xml
./dp2 dtbook-to-epub3 --i-source /tmp/input/great_painters_dtbook_2005-3-test/greatpainters.xml --output /tmp/output 
```
1. Unzipped the output result epub, greatpainters2.xml corresponding line (now part of line 3) reads as follows:

``` xml
<h1 id="d8676e25-0"><em>CHAPTER 1</em><em>THE LAST JUDGEMENT (MICHAEL ANGELO)</em></h1>
```

Notice that when this is viewed with an HTML/XML viewer, the text will read 

```
CHAPTER 1THE LAST JUDGEMENT (MICHAEL ANGELO) 
```

with no space in between, although the original DTBook chapter title with the space was valid.

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-scripts/pull/104

**Comment by bertfrees** [comment]
Hmm, I didn't fix this one after all.

**Comment by rdeltour** [comment]
@bertfrees if this is still opened, we should move it out of v1.10.2 and add to the next release so that we can close the milestone.

**Comment by bertfrees** [comment]
@rdeltour This is related to a commit you did in zedai-to-html: https://github.com/daisy/pipeline-scripts/commit/df9c89f873e057f1b1bab832265f899952fd6a71. This is where you added:

```xml
<xsl:strip-space elements="*"/>
```

Why did you add it? I can remove it and all the tests will still pass, although that doesn't mean much because XSpec ignores whitespace-only nodes unless you have a `preserve-space` attribute.

**Comment by rdeltour** [comment]
> Why did you add it?

TBH I can’t remember what I had in mind back then. Might just be a habit.

It feels pretty safe and sound to remove this line!

**Comment by bertfrees** [comment]
OK. The other part of the problem seems to be in moveout-generic.xsl in dtbook-to-zedai. Whitespace-only text nodes are explicitly removed there, but it's not really clear why.

https://github.com/daisy/pipeline-scripts/blob/master/dtbook-to-zedai/src/main/resources/xml/moveout-generic.xsl#L17

**Comment by bertfrees** [comment]
AFAIKS the stripping was not done before https://github.com/daisy/pipeline-scripts/commit/e3f275199b4d684461443bcf3d21ea3e4aee534d.

**Comment by bertfrees** [comment]
The whitespace nodes are probably ignored in order to not create superfluous parts like in this case:

```xml
<p>
    Part A
    <imggroup id="d1e63">
        <img id="d1e65" src="abc.jpg" alt="abc"/>
        <caption id="d1e67">i am a caption</caption>
    </imggroup>
</p>
```


```xml
<p>
    Part A
</p>
<p>
    <imggroup id="d1e63">
        <img id="d1e65" src="abc.jpg" alt="abc"/>
        <caption id="d1e67">i am a caption</caption>
    </imggroup>
</p>
<p>
</p>
```

**Comment by bertfrees** [comment]
@rdeltour Does this solution look OK to you? https://github.com/daisy/pipeline/commit/2d26da681cc3d6f85ac9e44a35771503ef85014f#diff-f5a25bc471149a460e21062d407b3485

**Comment by bertfrees** [comment]
@marisademeglio I should also ask you.

**Comment by bertfrees** [comment]
Fixed in https://github.com/daisy/pipeline-scripts/commit/8f4da41e9b08d9c65a7c09855784d1c81ed7b296
